version: "3.9"

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: mcly-postgres
    environment:
      POSTGRES_DB: mcly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

