drop all objects;

create table store (
    id bigint generated by default as identity primary key,
    code varchar(32) not null unique,
    name varchar(128) not null,
    city varchar(64),
    address varchar(255)
);

create table member (
    id bigint generated by default as identity primary key,
    store_id bigint references store(id),
    name varchar(64) not null,
    phone varchar(32) not null unique,
    level varchar(32) not null default 'NORMAL',
    face_bound boolean not null default false,
    risk_tag varchar(32) not null default 'NORMAL'
);

create table pet_profile (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    name varchar(64) not null,
    species varchar(32) not null,
    breed varchar(64),
    gender varchar(16),
    birthday date,
    weight numeric(8,2)
);

create table membership_card (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    card_type varchar(32) not null,
    store_id bigint references store(id),
    status varchar(32) not null,
    valid_from timestamp not null,
    valid_to timestamp not null,
    face_bound boolean not null default false
);

create table reservation (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    store_id bigint not null references store(id),
    reservation_type varchar(32) not null,
    reservation_date date not null,
    time_slot varchar(32) not null,
    status varchar(32) not null,
    amount numeric(12,2) not null default 0,
    source varchar(32) not null default 'CUSTOMER_MINI'
);

create table customer_order (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    store_id bigint not null references store(id),
    reservation_id bigint references reservation(id),
    order_no varchar(64) not null unique,
    order_type varchar(32) not null,
    status varchar(32) not null,
    payable_amount numeric(12,2) not null default 0,
    paid_amount numeric(12,2) not null default 0
);
