drop all objects;

create table store (
    id bigint generated by default as identity primary key,
    code varchar(32) not null unique,
    name varchar(128) not null,
    city varchar(64),
    address varchar(255)
);

create table staff (
    id bigint generated by default as identity primary key,
    store_id bigint references store(id),
    name varchar(64) not null,
    phone varchar(32) not null unique,
    role_code varchar(32) not null,
    status varchar(32) not null default 'ACTIVE'
);

create table member (
    id bigint generated by default as identity primary key,
    store_id bigint references store(id),
    name varchar(64) not null,
    phone varchar(32) not null unique,
    level varchar(32) not null default 'NORMAL',
    face_bound boolean not null default false,
    risk_tag varchar(32) not null default 'NORMAL'
);

create table pet_profile (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    name varchar(64) not null,
    species varchar(32) not null,
    breed varchar(64),
    gender varchar(16),
    birthday date,
    weight numeric(8,2)
);

create table membership_card (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    card_type varchar(32) not null,
    store_id bigint references store(id),
    status varchar(32) not null,
    valid_from timestamp not null,
    valid_to timestamp not null,
    face_bound boolean not null default false
);

create table reservation (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    store_id bigint not null references store(id),
    pet_id bigint references pet_profile(id),
    reservation_type varchar(32) not null,
    reservation_date date not null,
    time_slot varchar(32) not null,
    status varchar(32) not null,
    amount numeric(12,2) not null default 0,
    source varchar(32) not null default 'CUSTOMER_MINI'
);

create table customer_order (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    store_id bigint not null references store(id),
    reservation_id bigint references reservation(id),
    order_no varchar(64) not null unique,
    order_type varchar(32) not null,
    status varchar(32) not null,
    payable_amount numeric(12,2) not null default 0,
    paid_amount numeric(12,2) not null default 0
);

create table gate_device (
    id bigint generated by default as identity primary key,
    store_id bigint not null references store(id),
    code varchar(64) not null unique,
    name varchar(128) not null,
    device_type varchar(32) not null default 'FACE_GATE',
    status varchar(32) not null default 'ONLINE',
    last_seen_at timestamp
);

create table pass_entitlement (
    id bigint generated by default as identity primary key,
    member_id bigint not null references member(id),
    store_id bigint not null references store(id),
    source_type varchar(32) not null,
    source_id bigint not null,
    status varchar(32) not null,
    valid_from timestamp not null,
    valid_to timestamp not null,
    reentry_policy varchar(32) not null
);

create table entry_exit_record (
    id bigint generated by default as identity primary key,
    member_id bigint references member(id),
    store_id bigint not null references store(id),
    gate_device_id bigint references gate_device(id),
    direction varchar(16) not null,
    result varchar(32) not null,
    risk_flag boolean not null default false,
    reason_code varchar(64),
    occurred_at timestamp not null default current_timestamp
);

create table manual_release_record (
    id bigint generated by default as identity primary key,
    store_id bigint not null references store(id),
    member_id bigint references member(id),
    order_id bigint references customer_order(id),
    staff_id bigint not null references staff(id),
    reason varchar(255) not null,
    risk_flag boolean not null default false,
    created_at timestamp not null default current_timestamp
);

create table risk_event (
    id bigint generated by default as identity primary key,
    store_id bigint references store(id),
    event_type varchar(64) not null,
    event_level varchar(16) not null,
    subject_type varchar(32) not null,
    subject_id bigint,
    content varchar(1024),
    status varchar(32) not null default 'OPEN',
    created_at timestamp not null default current_timestamp
);

create index idx_reservation_pet on reservation(pet_id);
create index idx_pass_entitlement_source on pass_entitlement(source_type, source_id);
